### ISSUE TITLE
Gprofiler error message

### ISSUE THREAD

**Issue by jblandis** [Ylefol/TimeSeriesAnalysis#13]
I'm running the TiSA script using the Glycine max reference genome. I set the organisms to 'gmax'. When running through the Gprofiler part of the script, I get the following messages:

running Gprofiler on PART clusters
Gprofiler for C1
Gprofiler for C2
No results to show
Please make sure that the organism is correct or set significant = FALSE
Gprofiler for C3
Gprofiler for C4

For whatever reason there doesn't seem to be anything in C2. Is this what is causing the error and not specifying the reference organism correctly? 

One additional question, not related to Gprofiler. For the PCA analyses, is it possible to plot further PCs than just PC1 vs PC2? Would it be possible to do PC2 vs PC3 and PC3 vs PC4?

The rest of the scripts and plots appear to work, which is super awesome. Thank you for putting together such a great resource.

**Comment by Ylefol** [comment]
Hello,

I'm unfamiliar with the Glycine max reference. However in regards to the error since it is only occuring in one of the clusters (C2) it likely means that Gprofiler could not map any of the genes in that cluster to any of it's processes, functions ect...
In human/murine studies this is usually an indication that the cluster has many long non coding RNAs or uncharacterized genes, which in both cases are almost never associated to gene sets. Perhaps this could be the same thing with the Glycine max reference?
Essentially it looks like it isn't a error in the code but rather just the content of the cluster which doesn't map to anything in particular.

As for the PCA it isn't possible as of now, though it would be a good idea to add it and it wouldn't be difficult to add some parameters to enable it. My week is pretty packed but I've put this on my to do list for next week and I can give you an update on this issue/page once I've pushed the modification.

**Comment by jblandis** [comment]
Thanks for the feedback. My assumption about Gprofiler was the same as yours (a cluster that didn't have anything mapping); I just wanted to make sure this didn't look like an error in specifying the organism. That would be fantastic if its possible to adjust on the PCA side of things. No major rush at all, we still have a lot to wade through with the rest of the script and the results that were generated.

**Comment by Ylefol** [comment]
Hello,

I've now made the changes to the function and aligned it with a new release so you will have to re-install the package.

There is an added parameter to 'plot_PCA_TS' called pcsToUse. The parameter takes in a vector of two integers where the first integer will be the Principal Component for the x axis while the second will be for the yaxis.

So for the standard PC1 PC2 we would use c(1,2) as the entry for the parameter.

I hope this helps :)

I'll close this issue for now but feel free to re-open it if another problem arises, or a new one if it is a different type of issue.
