### ISSUE TITLE
Murine data execution example

### ISSUE THREAD

**Issue by akiton-bay** [Ylefol/TimeSeriesAnalysis#6]
The data I want to analyze does not have replication. It seems that the only execution example is PBMC, but could you also create an execution example for murine? It would also be helpful if you could also upload the input data file.

**Comment by Ylefol** [comment]
Hello,

The murine data had previously been removed to make room on the repository, however I could certainly add it back in.
I'll add it to my todo list.

The murine dataset was run by merging timepoint together, and this was simply done in the sample file. 

For example, if M1 and M2 are murine samples for day 1 and day 2 respectively. They would be merged under the new timepoint of day 1.5.

The reason this route has to be utilized is that differential gene expression is not supported with single replicates on both the control and experimental side.

I'll update once I've gotten the murine vignette back up and running, this may take a week or two due to a large number of items on my to do list.
In the mean time here is the csv file illustrating how we merged the replicates/timepoints. 
[murine_sample_file.csv](https://github.com/Ylefol/TimeSeriesAnalysis/files/14081248/murine_sample_file.csv)

**Comment by Ylefol** [comment]
Hello,

Sorry for the wait. The murine data can now be written to your directory via the 'write_data_to_dir' function while specifying the 'data_name' as murine. This can be accessed with the latest push (version 1.02.01)

For now I'll close this issue, feel free to re-open it (or another one) if something else comes up.

-Yohan
